#!/bin/bash
# Do not edit! Automatically generated by libbuild

# Deploy an Ingress controller
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install ingress bitnami/nginx-ingress-controller

# Deploy a Lets Encrypt Cert Manager
helm repo add jetstack https://charts.jetstack.io
kubectl create namespace cert-manager
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.crds.yaml
kubectl apply -f certmanager.yaml
helm install cert-manager --namespace cert-manager jetstack/cert-manager --version v0.14.1

# Deploy example TLS app
helm install ghost bitnami/ghost --set ghostHost=labx.thescottsweb.com,serviceType=ClusterIP

# Create ingress
kubectl apply -f ingress.yaml

